### PR TITLE
Fix some of the image alt texts

### LINKED ISSUE #707: Screen readers should skip all the irrelevant images
Either provide an empty `alt=""` text or hide the images from screen readers otherwise.

### PR DESCRIPTION
**Pull request by juhakujala**
Add an empty alt tag for images in comments since it's impossible
to give the image an alt tag. This will make the screen readers skip
these images.

Define alt text for main hearing image: If there's no title or caption
provided, use an empty alt tag. If a caption is defined but no title, use
caption. If the title for image is defined, it will be used instead.

Also don't display the image caption element at all if no caption is
provided.

Fixes #707

### CODE REVIEW

File: src/components/Hearing/Section/SectionImage.js [hunk 1]
```diff
@@ -3,12 +3,22 @@ import PropTypes from 'prop-types';
...
 export const SectionImageComponent = ({image, caption, title, showLightbox, openLightbox, closeLightbox}) => {
+  const defineImageAlt = () => {
+    let imageAlt = "";
+    if (caption) {
+      imageAlt = caption;
+    }
+    if (title) {
+      imageAlt = title;
+    }
+    return imageAlt;
```
Comment (farrukh8925) [inline src/components/Hearing/Section/SectionImage.js]: Shouldn't the caption take priority over title ? In general image alt terms ? because imageAlt in this case will almost always be title.

anywho. Perhaps this block can be a lot shorter without variable assignment.

```
const defineImageAlt = () => caption || title;
```

Comment (Rikuoja) [reply src/components/Hearing/Section/SectionImage.js]: In most of the current data, there is no title so the image caption is displayed as alt text.

However, in general, I believe caption to be always more descriptive than the image title, so I agree with @farrukh8925 that we should use the caption (or even better, alt text, if we want to add backend support for that).

**Comment by Rikuoja** [comment]
Anyway, I added the `alt_text` field to backend images, so it may be used if we wish to add the option to add alt text in the editor UI in the future.

Therefore, I suggest the order of precedence is `alt_text || caption || title`.

**Comment by juhakujala** [comment]
Thanks for the comments! I fixed it to be `alt_text || caption || title || ''` since all of the three values can be undefined so we need the empty string as a backup.
